# C++ language configuration

[[language]]
name = "cpp"
auto-format = true
language-servers = ["clangd"]
formatter = { command = "clang-format" }

[language-server.clangd]
command = "clangd"
args = [
  "--background-index",
  "--clang-tidy",
  "--completion-style=detailed",
  "--header-insertion=never",
  "--suggest-missing-includes",
  "--compile-commands-dir=build",
  "--query-driver=**/*clang++,**/*g++"
]

# Nix language configuration

[[language]]
name = "nix"
auto-format = true
language-servers = ["nixd"]
formatter = { command = "nixfmt" }

[language-server.nixd]
command = "nixd"

[language-server.nixd.config.formatting]
command = ["nixfmt"]
